config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    require 'net/http'
    if user_id = params[:user_id]
      user_id = params[:user_id]
      params = URI.encode_www_form({user_id: user_id})
      uri = URI.parse("http://localhost:3000/users/2.json")      
      response = Net::HTTP.get_response(uri)
      binding.pry
      result = JSON.parse(response.body)      
      binding.pry
      if result["user"]
        @user_id = result["user"]["id"]
        @name = result["user"]["name"]
        @email = result["user"]["email"]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserIdSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :user_id, class: "search_form", placeholder: "ユーザーIDを入力してください"%>
    <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/search/search.html.erb
<p>
    ユーザーID：<%= @user_id %>
</p>
<p>
    ユーザー名：<%= @name %>
</p>
<p>
    Email：<%= @email %>
</p>